package agent

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"strings"
	"text/template"

	"github.com/phs/dark-factory/internal/config"
	"github.com/phs/dark-factory/prompts"
)

// Prompts holds the loaded template text for each agent prompt.
type Prompts struct {
	Implementer      string
	ImplementerRetry string
	Reviewer         string
	QualityReviewer  string
	SpecGenerator    string
	Punchlist        string
	VerifyFix        string
	Recon            string
}

// PromptData contains the values substituted into prompt templates.
type PromptData struct {
	IssueNumber            int
	IssueTitle             string
	IssueBody              string
	Slug                   string
	Repo                   string
	PRNumber               int
	BuildCommand           string
	TestCommand            string
	ProtectedPaths         string
	GeneratedPaths         string
	ScenarioDir            string
	ReviewDir              string
	VerifyErrors           string
	BranchExists           bool
	StrictnessDirective    string
	EnforceArchitecture    bool
	ArchitectureDocContent string
	ArchitectureJSON       string
	ConventionsDocContent  string
	HasScenarioSpec        bool
	// ModuleContext describes the configured modules and their dependency
	// relationships. Empty when no modules are configured.
	ModuleContext string
	// ComposeServices describes the Docker Compose services available in the
	// test environment. Empty when no services are configured.
	ComposeServices string
	// ReviewFeedback holds human reviewer comments injected directly into the
	// retry prompt. Non-empty only for watch-initiated fix cycles.
	ReviewFeedback string
	// BaseBranch, when non-empty, is the target branch for PRs. Prompts use
	// this to branch off origin/<BaseBranch> and pass --base <BaseBranch> to
	// gh pr create.
	BaseBranch string
	// ReconBrief holds the output from the recon agent. When non-empty it is
	// injected into the implementer prompt as pre-implementation context.
	// Not set by newPromptData() — set by the caller after running the recon
	// agent.
	ReconBrief string
	// HandoffContext, when non-empty, signals a fresh-session retry. It
	// contains a chronological summary of prior implementation and review
	// notes extracted from PR comments so the new agent understands what was
	// tried and what failed without inheriting a degraded context window.
	HandoffContext string
	// SharedRules holds the universally shared subset of CRITICAL RULES —
	// protected paths and scenario dir protection. Generated by newPromptData
	// from ProtectedPaths and ScenarioDir config values. Agent-specific rules
	// (branch creation, ReviewDir mandates, generated paths) remain in each
	// individual prompt template.
	SharedRules string
}

// loadPromptFile reads a prompt from the config path if set, otherwise from
// the embedded default. name is the embedded filename (e.g. "implementer.txt").
func loadPromptFile(configPath, name string) (string, error) {
	if configPath != "" {
		data, err := os.ReadFile(configPath)
		if err != nil {
			return "", fmt.Errorf("reading prompt %q: %w", configPath, err)
		}
		return string(data), nil
	}
	data, err := prompts.FS.ReadFile(name)
	if err != nil {
		return "", fmt.Errorf("reading embedded prompt %q: %w", name, err)
	}
	return string(data), nil
}

// LoadPrompts reads prompt template files, using embedded defaults for any
// paths not specified in the config.
func LoadPrompts(cfg *config.Config) (*Prompts, error) {
	impl, err := loadPromptFile(cfg.Prompts.Implementer, "implementer.txt")
	if err != nil {
		return nil, err
	}

	retry, err := loadPromptFile(cfg.Prompts.ImplementerRetry, "implementer_retry.txt")
	if err != nil {
		return nil, err
	}

	rev, err := loadPromptFile(cfg.Prompts.Reviewer, "reviewer.txt")
	if err != nil {
		return nil, err
	}

	p := &Prompts{
		Implementer:      impl,
		ImplementerRetry: retry,
		Reviewer:         rev,
	}

	// QualityReviewer is optional — load from config or embedded default.
	qualRev, err := loadPromptFile(cfg.Prompts.QualityReviewer, "quality_reviewer.txt")
	if err != nil {
		p.QualityReviewer = ""
	} else {
		p.QualityReviewer = qualRev
	}

	// SpecGenerator is optional — load from config or embedded default.
	specGen, err := loadPromptFile(cfg.Prompts.SpecGenerator, "spec_generator.txt")
	if err != nil {
		// If the embedded file doesn't exist either, just leave it empty.
		p.SpecGenerator = ""
	} else {
		p.SpecGenerator = specGen
	}

	// Punchlist is optional — load from config or embedded default.
	pl, err := loadPromptFile(cfg.Prompts.Punchlist, "punchlist.txt")
	if err != nil {
		p.Punchlist = ""
	} else {
		p.Punchlist = pl
	}

	// VerifyFix is optional — load from config or embedded default.
	vf, err := loadPromptFile(cfg.Prompts.VerifyFix, "verify_fix.txt")
	if err != nil {
		p.VerifyFix = ""
	} else {
		p.VerifyFix = vf
	}

	// Recon is optional — load from config or embedded default.
	recon, err := loadPromptFile(cfg.Prompts.Recon, "recon.txt")
	if err != nil {
		p.Recon = ""
	} else {
		p.Recon = recon
	}

	return p, nil
}

// RenderPrompt executes a text/template against the given data and returns
// the rendered string.
func RenderPrompt(tmplText string, data PromptData) (string, error) {
	t, err := template.New("prompt").Parse(tmplText)
	if err != nil {
		return "", fmt.Errorf("parsing prompt template: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing prompt template: %w", err)
	}
	return buf.String(), nil
}

// slugRe matches characters that are not alphanumeric or hyphens.
var slugRe = regexp.MustCompile(`[^a-z0-9]+`)

// Slugify converts a string into a branch-name-safe slug.
// It lowercases, replaces non-alphanumeric runs with hyphens, and trims.
func Slugify(s string) string {
	s = strings.ToLower(s)
	s = slugRe.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	return s
}
